name: "Required workflow"
on:
  pull_request:

permissions:
  contents: read

jobs:
  required-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Require
        run: false

# Add a comment
# Add a comment
